[project]
site_name = "Crestr Documentation"
repo_url = "https://github.com/abdlfc11/Crestr-Hiking-App"
repo_name = "Crestr Hiking App"

# Theme configuration
theme.name = "material"
theme.logo = "assets/images/Crest-Logo.png"
theme.variant = "modern"
theme.favicon = "favicon.ico"

theme.features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.expand",
    "content.code.copy",
    "content.code.annotate", # Good for technical docs
    "content.tabs.link",  # Better internal navigation
    "navigation.top", # Back to top button 
]

[project.theme.icon]
repo = "fontawesome/brands/github"

# Palette (light + dark)
[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "amber"

[project.theme.palette.toggle]
icon = "material/brightness-7"
name = "Switch to Dark Mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "amber"

[project.theme.palette.toggle]
icon = "material/weather-night"
name = "Switch to Light Mode"


# Navigation
[[project.nav]]
Home = "index.md"

[[project.nav]]
"Crestr App" = "https://crestr.co.uk"

[[project.nav]]
"User Guide" = [
    { "Getting Started" = "user/getting-started.md" },
    { "Automatic Routing" = "user/automatic-routing.md" },
    { "Manual Routing" = "user/manual-routing.md" },
    { "Exporting Routes" = "user/exporting-routes.md" }
]

[[project.nav]]
"Technical" = [
    { "Action Log Codes" = "technical/action_log_codes.md" },
    { "Data Preprocessing" = "technical/data-preprocessing.md" },
    { "Tech Stack" = "technical/tech-stack.md" },
    { "Architecture Overview" = "technical/architecture.md" },
    { "Routing Engine (A*)" = "technical/routing-engine.md" },
    { "KDTree" = "technical/kdtree.md" },
    { "Elevation Pipeline" = "technical/elevation.md" },
    { "Backend API" = "technical/backend-api.md" },
    { "Frontend Architecture" = "technical/frontend-architecture.md" }
]

[[project.nav]]
"Roadmap" = [
    { "Overview" = "roadmap/overview.md" },
    { "2025" = "roadmap/2025.md" },
    { "2026" = "roadmap/2026.md" },
    { "2027" = "roadmap/2027.md" }
]


# Plugins
project.plugins = ["search", "git-revision-date-localized"] 

# Markdown extensions
project.markdown_extensions = [
    "attr_list",
    "admonition",
    "pymdownx.details",
    "pymdownx.superfences",
]

[extra]
homepage = "https://crestr.co.uk"